### ISSUE TITLE
can't find config file if run from outside cwd 

### ISSUE THREAD

**Issue by ghost** [tym-xqo/jot#5]
As a jot user, I want to publish from a symlink that's in my $PATH, but `config.yml` is opened as unqualified local file. This should be fixed so that in can invoke the script as desired.

**Comment by tym-xqo** [comment]
Hey, it wasn't just the config - we have to load _jot, template, and index files also. There seem to be a number of answers to this floating around, but `sys.path[0]` works for me. Fixed in https://github.com/yagermadden/jot/commit/5a91e6d4b0881ca9647a5cac1cc6faa246d66ad2

**Comment by ghost** [comment]
Not merging to master yet, while I wait for argparse business, but the fix works: published on laptop and from AWS. I myself using this version in production.

**Comment by ghost** [comment]
Fixed in https://github.com/yagermadden/jot/commit/5a91e6d4b0881ca9647a5cac1cc6faa246d66ad2
